# Generated by Django 4.2.16 on 2024-11-02 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='unit',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='projectelement',
            name='description',
            field=models.TextField(default='None'),
        ),
    ]
